spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-microservice-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer